// Generated by Igo Elf 2004-11-2 23:36:00
var gameRecords = "B[pd];W[dp];B[cd];W[pq];B[po];W[qo];B[qn];W[qp];B[pn];W[nq];B[pj];W[ed];B[gc];W[df];B[ec];W[dc];B[dd];W[fc];B[eb];W[cc];B[fb];W[bd];B[ee];W[de];B[fd];W[ce];B[ed];W[ef];B[fp];W[fq];B[gq];W[eq];B[np];W[mp];B[gp];W[kq];B[do];W[co];B[cn];W[eo];B[dn];W[cp];B[ep];W[fn];B[jp];W[kp];B[el];W[fl];B[fk];W[gl];B[ci];W[ek];B[fj];W[dl];B[em];W[dj];B[di];W[cm];B[bn];W[bm];B[ck];W[dk];B[dm];W[cj];B[bk];W[bj];B[bi];W[ak];B[ai];W[fm];B[an];W[am];B[aj];W[bo];B[ej];W[cl];B[al];W[jo];B[io];W[in];B[jn];W[ko];B[hn];W[im];B[hm];W[hl];B[il];W[jm];B[jl];W[km];B[hk];W[gk];B[hj];W[gj];B[gi];W[fi];B[ei];W[hi];B[gh];W[ij];B[ik];W[kl];B[jk];W[jj];B[kk];";
var gameComments = "86,这里即使白棋封住也不行，黑棋竟然有有强烈的反击的手段！;105,至此白棋竟然由于征子不利而失败...\n\n值得注意的是，A位打并不是先手\n黑棋可以B位反打...;";
var gameLabels = "105,Ａ[ho];105,Ｂ[go];";
var gameStartIndex = 85;
